config/routes.rb
Rails.application.routes.draw do
  resources :dudes

  devise_for :people
  resources :people

  devise_for :students
  resources :students
  devise_for :users
  resources :courses
  post 'courses/addfriend', :to => 'courses#addfriend'
  post 'courses/acceptfriend', :to => 'courses#acceptfriend'

   root 'courses#index'

end

app/models/dude.rb
class Dude < ActiveRecord::Base
end

app/controllers/dudes_controller.rb
class DudesController < ApplicationController
  before_action :set_dude, only: [:show, :edit, :update, :destroy]

  # GET /dudes
  # GET /dudes.json
  def index
    @dudes = Dude.all
  end

  # GET /dudes/1
  # GET /dudes/1.json
  def show
  end

  # GET /dudes/new
  def new
    @dude = Dude.new
  end

  # GET /dudes/1/edit
  def edit
  end

  # POST /dudes
  # POST /dudes.json
  def create
    @dude = Dude.new(dude_params)

    respond_to do |format|
      if @dude.save
        format.html { redirect_to @dude, notice: 'Dude was successfully created.' }
        format.json { render :show, status: :created, location: @dude }
      else
        format.html { render :new }
        format.json { render json: @dude.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dudes/1
  # PATCH/PUT /dudes/1.json
  def update
    respond_to do |format|
      if @dude.update(dude_params)
        format.html { redirect_to @dude, notice: 'Dude was successfully updated.' }
        format.json { render :show, status: :ok, location: @dude }
      else
        format.html { render :edit }
        format.json { render json: @dude.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dudes/1
  # DELETE /dudes/1.json
  def destroy
    @dude.destroy
    respond_to do |format|
      format.html { redirect_to dudes_url, notice: 'Dude was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dude
      @dude = Dude.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dude_params
      params.require(:dude).permit(:name)
    end
end

app/helpers/dudes_helper.rb
module DudesHelper
end

app/views/dudes/_form.html.erb
<%= form_for(@dude) do |f| %>
  <% if @dude.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dude.errors.count, "error") %> prohibited this dude from being saved:</h2>

      <ul>
      <% @dude.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dudes/edit.html.erb
<h1>Editing dude</h1>

<%= render 'form' %>

<%= link_to 'Show', @dude %> |
<%= link_to 'Back', dudes_path %>

app/views/dudes/index.html.erb
<h1>Listing dudes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dudes.each do |dude| %>
      <tr>
        <td><%= dude.name %></td>
        <td><%= link_to 'Show', dude %></td>
        <td><%= link_to 'Edit', edit_dude_path(dude) %></td>
        <td><%= link_to 'Destroy', dude, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dude', new_dude_path %>

app/views/dudes/new.html.erb
<h1>New dude</h1>

<%= render 'form' %>

<%= link_to 'Back', dudes_path %>

app/views/dudes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dude.name %>
</p>

<%= link_to 'Edit', edit_dude_path(@dude) %> |
<%= link_to 'Back', dudes_path %>