config/routes.rb
Rails.application.routes.draw do
  resources :dudes

  devise_for :people
  resources :people

  devise_for :students
  resources :students
  devise_for :users
  resources :courses
  post 'courses/addfriend', :to => 'courses#addfriend'
  post 'courses/acceptfriend', :to => 'courses#acceptfriend'

   root 'courses#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AcesNet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Acesnet (Hack Duke 2015, John Dai)</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
          <% if person_signed_in?%>
	<li><a href="#">Welcome <%= current_person.email %>!</a></li>
	<li class="button">
		<%= link_to('Logout', destroy_person_session_path, :method => :delete) %>
		</li>
<% end %>
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <!--
 <nav class="navbar navbar navbar-fixed-top" role="navigation">
 	<div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">AcesNet</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
<% if person_signed_in?%>
	<li>Welcome <%= current_person.email %>!</li>
	<li class="button">
		<%= link_to('Logout', destroy_person_session_path, :method => :delete) %>
		</li>
<% end %>
            </ul>
            </div>
            </div>
    </nav>-->
<div class="container">
<% if !notice.nil? %>
	<p class="notice alert-info" role="alert"><%= notice %></p>
<% end %>
<% if !alert.nil? %>
	<p class="alert alert-warning" role="alert"><%= alert %></p>
<% end %>
<%= yield %>
</div>
</body>
</html>